name: Cleanup PR

on:
  repository_dispatch:
    types: [cleanup-cloud]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: teableio/teable-ee
          token: ${{ secrets.PACKAGES_KEY }}
          submodules: 'true'

      - name: Create deployment YAML
        env:
          INSTANCE_NAME: pr-cloud-${{ github.event.pull_request.number }}
          INSTANCE_DOMAIN: pr-cloud-${{ github.event.pull_request.number }}
          DISPLAY_NAME: "teable-pr-cloud-${{ github.event.pull_request.number }}"
          MAIN_IMAGE_REPOSITORY: registry.cn-shenzhen.aliyuncs.com/teable/teable-cloud
          DB_MIGRATE_IMAGE_REPOSITORY: registry.cn-shenzhen.aliyuncs.com/teable/teable-db-migrate-cloud
          IMAGE_TAG: ${{ steps.get_sha.outputs.sha }}-amd64
        run: |
          cp .github/workflows/templates/preview-template.yaml deploy.yaml
          sed -i "s#__INSTANCE_NAME__#${{ env.INSTANCE_NAME }}#g" deploy.yaml
          sed -i "s#__INSTANCE_DOMAIN__#${{ env.INSTANCE_DOMAIN }}#g" deploy.yaml
          sed -i "s#__MAIN_IMAGE_REPOSITORY__#${{ env.MAIN_IMAGE_REPOSITORY }}#g" deploy.yaml
          sed -i "s#__DB_MIGRATE_IMAGE_REPOSITORY__#${{ env.DB_MIGRATE_IMAGE_REPOSITORY }}#g" deploy.yaml
          sed -i "s#__IMAGE_TAG__#${{ env.IMAGE_TAG }}#g" deploy.yaml
          sed -i "s#__DISPLAY_NAME__#${{ env.DISPLAY_NAME }}#g" deploy.yaml

      - name: Delete deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete -f deploy.yaml --ignore-not-found=true

      - name: Create cleanup status comment
        env:
          GH_TOKEN: ${{ secrets.PACKAGES_KEY }}
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest")
            const customOctokit = new Octokit({
              auth: process.env.GH_TOKEN
            })
            
            const prNumber = context.payload.pull_request.number;
            const mergeStatus = context.payload.pull_request.merged ? 'Merged' : 'Closed';
            
            const commentBody = `## 🧹 Preview Environment Cleanup
            * PR #${prNumber} has been ${mergeStatus}
            * Cloud preview environment has been deleted
            * Cleanup time: ${new Date().toISOString()}`;

            await customOctokit.rest.issues.createComment({
              owner: 'teableio',
              repo: 'teable-ee',
              issue_number: prNumber,
              body: commentBody
            });
