name: Test Feishu Notification (Simple)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    outputs:
      start_time: ${{ steps.start_time.outputs.start }}
      main_commit_sha: ${{ steps.get_main_commit.outputs.sha }}
      main_commit_author: ${{ steps.get_main_commit.outputs.author }}
      main_commit_message: ${{ steps.get_main_commit.outputs.message }}
      submodule_commit_sha: ${{ steps.get_submodule_commit.outputs.submodule_sha }}
      submodule_commit_author: ${{ steps.get_submodule_commit.outputs.submodule_author }}
      submodule_commit_message: ${{ steps.get_submodule_commit.outputs.submodule_message }}
    
    steps:
      - name: Record start time
        id: start_time
        run: echo "start=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: teableio/teable-ee
          token: ${{ secrets.PACKAGES_KEY }}
          submodules: "true"

      - name: Get teable-ee commit info
        id: get_main_commit
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT

      - name: Get community submodule commit info
        id: get_submodule_commit
        run: |
          cd community
          echo "submodule_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "submodule_message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
          echo "submodule_author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT

      - name: Simulate build process (uncomment exit 1 to test failure)
        run: |
          echo "Simulating build process..."
          sleep 5
          # Uncomment the line below to test failure notification
          # exit 1

  notify:
    needs: test-build
    if: always()
    uses: ./.github/workflows/notify-feishu.yaml
    with:
      workflow_name: "Teable Test"
      workflow_status: ${{ needs.test-build.result }}
      start_time: ${{ needs.test-build.outputs.start_time }}
      main_commit_sha: ${{ needs.test-build.outputs.main_commit_sha }}
      main_commit_author: ${{ needs.test-build.outputs.main_commit_author }}
      main_commit_message: ${{ needs.test-build.outputs.main_commit_message }}
      submodule_commit_sha: ${{ needs.test-build.outputs.submodule_commit_sha }}
      submodule_commit_author: ${{ needs.test-build.outputs.submodule_commit_author }}
      submodule_commit_message: ${{ needs.test-build.outputs.submodule_commit_message }}
    secrets:
      LARK_BOT_URL: ${{ secrets.LARK_BOT_URL }}
